### ISSUE TITLE
挑個中譯小毛病

### ISSUE THREAD

**Issue by aboolou** [fjn308/rm-s04e03-amzn#1]
Dialogue: 0,0:19:11.70,0:19:13.70,Chn,,0,0,0,,然后就会出现一个巨牛逼的拧巴之处 像是\N{\rEng}and then this big awesome twist where there's, like,

"twist" 在此指劇情的大反轉，「擰巴」為誤譯。

**Comment by fjn308** [comment]
言之有理，多谢！

**Comment by fjn308** [comment]
兄弟我把要你的名字加上了啊，当时我刚开始探索github半会不会的，改完close了就把这事忘了，如果有得罪请多包涵！

**Comment by fjn308** [comment]
@aboolou
